language: elixir
elixir:
  - 1.1.0
addons:
  postgresql: '9.4'
before_script:
  - npm install -g brunch
  - npm install
  - brunch build --production
  - mix phoenix.digest
  - MIX_ENV=test mix do deps.get, deps.compile, ecto.create, ecto.migrate
after_success:
  - 'curl -H "Content-Type: application/json" --data ''{"source_type": "Branch", "source_name": "master"}'' -X POST $DOCKER_HUB_URL'